name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['7.2', '7.3', '7.4']
        laravel: ['5.8.*', '6.*']
        include:
          - laravel: '6.*'
            testbench: '4.*'
          - laravel: '5.8.*'
            testbench: '3.8.*'

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: common, curl, json, mbstring, zip, sqlite, pdo_sqlite
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-suggest

      - name: PHP Code Sniffer
        run: vendor/bin/phpcs

      - name: PHP Mess Detector
        run: vendor/bin/phpmd config,src text phpmd.xml

      - name: PHP Static Analysis Tool
        if: matrix.php == '7.4' && matrix.laravel == '6.*'
        run: vendor/bin/phpstan analyse

      - name: PHPUnit
        if: matrix.php != '7.4' || matrix.laravel != '6.*'
        run: vendor/bin/phpunit

      - name: PHPUnit + code coverage
        if: matrix.php == '7.4' && matrix.laravel == '6.*'
        run: |
          mkdir -p build/logs
          vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

      - name: Upload coverage to Coveralls
        if: matrix.php == '7.4' && matrix.laravel == '6.*'
        env:
          COVERALLS_RUN_LOCALLY: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          composer require php-coveralls/php-coveralls
          vendor/bin/php-coveralls -v --coverage_clover=build/logs/clover.xml
